minimum_pre_commit_version: 2.13.0
default_stages: [commit, push]
exclude: "^$"
#default_language_version:
#  python: python3.10

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: double-quote-string-fixer
      - id: name-tests-test
      #- id: detect-aws-credentials
      - id: detect-private-key
      - id: check-added-large-files
        types: ["python"]
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        types: ["python"]
  - repo: https://github.com/asottile/blacken-docs
    rev: 1.13.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==23.1.0]
        types: ["python"]
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
